/* code/sql/HW_AVG.sql */

DROP SCHEMA IF EXISTS HW_AVG;
CREATE SCHEMA HW_AVG;
USE HW_AVG;

CREATE TABLE TEST(
    Test INT
);

INSERT INTO TEST VALUES (null), (0), (10);

SELECT AVG(Test) FROM TEST;
-- Returns 5.0
