/* code/sql/HW_PERSON.sql */

DROP SCHEMA IF EXISTS HW_PERSON;
CREATE SCHEMA HW_PERSON;
USE HW_PERSON;

CREATE TABLE PERSON(
    ID VARCHAR(25) PRIMARY KEY,
    Name VARCHAR(25),
    Street VARCHAR(25),
    City VARCHAR(25),
    Seat VARCHAR(25),
    Position VARCHAR(25)
);

CREATE TABLE CAR(
    Vin VARCHAR(25) PRIMARY KEY,
    Make VARCHAR(25),
    Model VARCHAR(25),
    Year DATE,
    Driver VARCHAR(25),
    FOREIGN KEY (Driver) REFERENCES PERSON(ID)
        ON UPDATE CASCADE
    );

ALTER TABLE PERSON ADD FOREIGN KEY (Seat) REFERENCES car(Vin); 

CREATE TABLE CAR_INSURANCE(
    Policy_number VARCHAR(25) PRIMARY KEY,
    Company_name VARCHAR(25),
    Insured_car VARCHAR(25),
    FOREIGN KEY (Insured_car) REFERENCES CAR(Vin)
    );
    
CREATE TABLE PHONE(
    ID VARCHAR(25),
    Number VARCHAR(25),
    FOREIGN KEY (ID) REFERENCES PERSON(ID),
    PRIMARY KEY (ID, number)
    );
